# Generated by Django 5.1.5 on 2025-03-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reserved_seats',
            field=models.TextField(),
        ),
    ]
