# Generated by Django 5.1.7 on 2025-03-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_booking_reserved_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
