# Generated by Django 5.1.5 on 2025-03-25 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_ewallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=1)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ewallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ewallet')),
            ],
        ),
    ]
