# Generated by Django 5.1.7 on 2025-04-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='stops_coordinates',
            field=models.CharField(default={1, 2}, max_length=255),
            preserve_default=False,
        ),
    ]
