# Generated by Django 5.1.7 on 2025-04-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_schedule_stops_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_by',
            field=models.CharField(default='1', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
