# Generated by Django 5.1.7 on 2025-04-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_transaction_transaction_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_by',
            new_name='transaction_rel_id',
        ),
    ]
